apm-server:
  host: "0.0.0.0:8200"
  kibana:
    enabled: true
    username: "elastic"
    password: "changme"
output.elasticsearch:
  hosts: ["localhost:9200"]
  enabled: true
  username: "elastic"
  password: "changme"